# Generated by Django 5.2.3 on 2025-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='mapa_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('SD', 'Salida a Descanso'), ('VD', 'Volver de Descanso'), ('S', 'Salida')], max_length=2),
        ),
    ]
